[package]
name = "aienos-kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "AIENOS bare-metal no_std kernel substrate for aarch64"

[features]
default = ["std"]
std = []
seed0b-test-anchor = ["aienos-artifact/seed0b-test-anchor"]

[dependencies]
aienos-accel = { path = "../aienos-accel" }
aienos-artifact = { path = "../aienos-artifact" }
aienos-crypto = { path = "../aienos-crypto" }

[dev-dependencies]
ed25519-dalek = { version = "=2.2.0", default-features = false, features = ["fast"] }
