#!/bin/bash
# gen-fixtures-h.sh: turn the fixture scripts into the C header core/osh_fixtures.h used by the kernel self-test
# (CK_OSH_TEST). od + sed only, no scripting language. Usage: gen-fixtures-h.sh TRACE_DIR OUT_H
# Each tNN.sh may have the optional sidecars of omega tests/osh/osh_trace.c: tNN.status (fake pipeline statuses) and
# tNN.args (positional parameters, one per line). They are embedded as raw bytes; a sidecar without its .sh is an error.
# QEMU (aarch64 virt), TEST signer, not physical.
set -eu
export LC_ALL=C
dir=${1:?TRACE_DIR}
out=${2:?OUT_H}
for f in "$dir"/*.status "$dir"/*.args; do
    [[ -e "$f" ]] || continue
    [[ -e "${f%.*}.sh" ]] || { echo "gen-fixtures-h.sh: $f has no ${f%.*}.sh" >&2; exit 1; }
done
bytes() { # NAME FILE
    echo "static const unsigned char $1[] = {"
    od -An -v -tu1 "$2" | sed 's/^ *//; s/  */,/g; s/$/,/'
    echo "0};"
}
{
    echo "/* GENERATED by tests/fixtures/osh/gen-fixtures-h.sh from the fixture scripts in tests/fixtures/osh/trace. Do not edit. */"
    echo "#ifndef AIENOS_CK_OSH_FIXTURES_H"
    echo "#define AIENOS_CK_OSH_FIXTURES_H"
    i=0
    for f in "$dir"/*.sh; do
        bytes "osh_fx_$i" "$f"
        [[ -e "${f%.sh}.status" ]] && bytes "osh_fx_${i}_status" "${f%.sh}.status"
        [[ -e "${f%.sh}.args" ]] && bytes "osh_fx_${i}_args" "${f%.sh}.args"
        i=$((i + 1))
    done
    echo "static const struct {"
    echo "    const char *name;"
    echo "    const unsigned char *text;"
    echo "    unsigned long len;"
    echo "    const unsigned char *status; /* NULL: no .status sidecar */"
    echo "    unsigned long status_len;"
    echo "    const unsigned char *args; /* NULL: no .args sidecar */"
    echo "    unsigned long args_len;"
    echo "} osh_fx[] = {"
    i=0
    for f in "$dir"/*.sh; do
        st="0, 0"
        ar="0, 0"
        [[ -e "${f%.sh}.status" ]] && st="osh_fx_${i}_status, sizeof osh_fx_${i}_status - 1"
        [[ -e "${f%.sh}.args" ]] && ar="osh_fx_${i}_args, sizeof osh_fx_${i}_args - 1"
        echo "    { \"$(basename "$f" .sh)\", osh_fx_$i, sizeof osh_fx_$i - 1, $st, $ar },"
        i=$((i + 1))
    done
    echo "};"
    echo "#endif"
} >"$out"
