#!/bin/bash
# gen-fixtures-h.sh: turn the fixture scripts into the C header core/osh_fixtures.h used by the kernel self-test
# (CK_OSH_TEST). od + sed only, no scripting language. Usage: gen-fixtures-h.sh TRACE_DIR OUT_H
# QEMU (aarch64 virt), TEST signer, not physical.
set -eu
export LC_ALL=C
dir=${1:?TRACE_DIR}
out=${2:?OUT_H}
{
    echo "/* GENERATED by tests/fixtures/osh/gen-fixtures-h.sh from the fixture scripts in tests/fixtures/osh/trace. Do not edit. */"
    echo "#ifndef AIENOS_CK_OSH_FIXTURES_H"
    echo "#define AIENOS_CK_OSH_FIXTURES_H"
    i=0
    for f in "$dir"/*.sh; do
        echo "static const unsigned char osh_fx_$i[] = {"
        od -An -v -tu1 "$f" | sed 's/^ *//; s/  */,/g; s/$/,/'
        echo "0};"
        i=$((i + 1))
    done
    echo "static const struct { const char *name; const unsigned char *text; unsigned long len; } osh_fx[] = {"
    i=0
    for f in "$dir"/*.sh; do
        echo "    { \"$(basename "$f" .sh)\", osh_fx_$i, sizeof osh_fx_$i - 1 },"
        i=$((i + 1))
    done
    echo "};"
    echo "#endif"
} >"$out"
