#!/bin/sh
# Flatten docs/adr/0015-golden-vectors.json into a C table of
# (section, key, value) rows, so the C test can check every field the frozen
# file carries (the same "every key asserted" rule as the Rust test).
# The JSON is the repo's own fixed file: one "key": value per line, nesting
# at most two levels (section -> unit_map). Anything else is refused.
# Usage: gen_golden.sh IN.json OUT.h
set -eu
in=$1
out=$2
awk '
function fail(m) { print "gen_golden: " m " at line " NR > "/dev/stderr"; bad = 1; exit 1 }
BEGIN { depth = 0; n = 0 }
{
  line = $0
  sub(/^[ \t]+/, "", line); sub(/[ \t]+$/, "", line)
  if (line == "{") { if (depth != 0) fail("unexpected {"); depth = 1; next }
  if (line ~ /^}[,]?$/) { depth--; next }
  if (line !~ /^"[^"]*": /) fail("unparsed line")
  key = line; sub(/^"/, "", key); sub(/": .*$/, "", key)
  val = line; sub(/^"[^"]*": /, "", val); sub(/,$/, "", val)
  if (val == "{") {
    depth++
    if (depth == 2) section = key
    else if (depth == 3) sub_key = key
    else fail("too deep")
    next
  }
  if (depth == 1) { sec = ""; k = key }
  else if (depth == 2) { sec = section; k = key }
  else { sec = section; k = sub_key "." key }
  if (val ~ /^"/) { isnum = 0; sub(/^"/, "", val); sub(/"$/, "", val); if (val ~ /["\\]/) fail("escape") }
  else if (val ~ /^[0-9]+$/) isnum = 1
  else fail("unsupported value")
  printf "    {\"%s\", \"%s\", \"%s\", %d},\n", sec, k, val, isnum
  n++
}
END { if (bad) exit 1; if (depth != 0) { print "gen_golden: unbalanced" > "/dev/stderr"; exit 1 } }
' "$in" > "$out.rows"
{
  echo "/* Generated by tests/gen_golden.sh from docs/adr/0015-golden-vectors.json. */"
  echo "typedef struct { const char *section, *key, *value; int is_number; } golden_row;"
  echo "static const golden_row GOLDEN[] = {"
  cat "$out.rows"
  echo "};"
  echo "#define GOLDEN_ROWS (sizeof GOLDEN / sizeof GOLDEN[0])"
} > "$out"
rm -f "$out.rows"
